"""The PostgreSQL schema — RAVEL's authoritative Project State.

Two conventions shape every table here:

**Aggregate roots get columns; the values inside them get JSONB.** A Project,
a DAG node, an Evidence row, an Artifact version is an entity — it is queried,
joined, and referenced by identifier, so it gets real columns with real
constraints. The values *inside* an aggregate (`BudgetLimits`, `AuthorityCheck`,
`CriterionResult`, a list of dependency identifiers) are never queried on their
own, so they are stored as JSONB and reconstituted by the domain models that
already validate them. Spreading them into columns would add a second place
where their shape is defined, which is a second place it can be wrong.

**Every closed vocabulary becomes a CHECK constraint generated from the Python
enum.** The values are interpolated from `StrEnum` members at import time, so
the constraint cannot drift from the domain model, and a value added to an enum
without a migration fails the test suite rather than reaching production.

Rows are never deleted. See `ravel.state.guards` for the triggers that enforce
that, and for the database-level transition checks.
"""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    MetaData,
    String,
    Text,
    UniqueConstraint,
    event,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

from ravel.domain.enums import (
    AccessStatus,
    ApprovalStatus,
    ClaimClass,
    CompletionStatus,
    Confidence,
    DecisionType,
    EvidenceSourceTier,
    FailureClass,
    FailurePolicy,
    JobState,
    JoinPolicy,
    NodeStatus,
    NodeType,
    ProjectStatus,
    ReviewCheckpoint,
    ReviewOutcome,
    TerminationStatus,
    UserRole,
    WorkerMessageKind,
)
from ravel.domain.events import ActorType, ProjectEventType
from ravel.domain.roles import AgentRole

#: Deterministic constraint names. Without this, PostgreSQL invents names and
#: a migration cannot drop a constraint it cannot predictably name.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for every RAVEL table."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def enum_check(column: str, vocabulary: type[StrEnum]) -> str:
    """A `CHECK` expression listing every value of a closed vocabulary.

    The values come from `StrEnum` members, never from user input, so the
    interpolation into SQL text carries no injection risk.
    """
    values = ", ".join(f"'{member.value}'" for member in vocabulary)
    return f"{column} IN ({values})"


def _enum_constraint(
    column: str, vocabulary: type[StrEnum], name: str | None = None
) -> CheckConstraint:
    """A named `CHECK` constraint over a closed vocabulary."""
    return CheckConstraint(enum_check(column, vocabulary), name=name or f"{column}_is_known")


#: UUID hex identifiers, generated by the domain layer.
ID = String(32)
#: Human-facing identifiers such as `P-1A2B3C4D`. Longer than an opaque id
#: because it carries a type prefix, and unique per table so a reader can quote
#: one unambiguously.
DISPLAY_ID = String(40)
#: Identifiers that may be supplied by a caller rather than generated.
REF = String(64)


# ── Identity and project ────────────────────────────────────────────────────


class UserRow(Base):
    """A human account."""

    __tablename__ = "users"

    user_id: Mapped[str] = mapped_column(ID, primary_key=True)
    username: Mapped[str] = mapped_column(String(128), nullable=False, unique=True)
    email: Mapped[str | None] = mapped_column(String(320))
    #: An argon2id digest. Never a password, never reversible.
    password_hash: Mapped[str | None] = mapped_column(Text)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class ProjectRow(Base):
    """One research project — the unit of isolation."""

    __tablename__ = "projects"
    __table_args__ = (
        _enum_constraint("status", ProjectStatus, "status_is_known"),
        Index("ix_projects_status", "status"),
    )

    project_id: Mapped[str] = mapped_column(ID, primary_key=True)
    display_id: Mapped[str] = mapped_column(DISPLAY_ID, nullable=False, unique=True)
    title: Mapped[str] = mapped_column(Text, nullable=False)
    objective: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    created_by: Mapped[str] = mapped_column(REF, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    paused_reason: Mapped[str | None] = mapped_column(Text)


class ProjectMembershipRow(Base):
    """What one user may do in one project.

    `role` lives here rather than on a token so that a revoked membership takes
    effect on the next request instead of at token expiry.
    """

    __tablename__ = "project_memberships"
    __table_args__ = (
        UniqueConstraint("project_id", "user_id", name="uq_project_memberships_one_role"),
        _enum_constraint("role", UserRole),
        Index("ix_project_memberships_user_id", "user_id"),
    )

    membership_id: Mapped[str] = mapped_column(ID, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    user_id: Mapped[str] = mapped_column(
        ID, ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False
    )
    role: Mapped[str] = mapped_column(String(32), nullable=False)
    granted_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    granted_by: Mapped[str | None] = mapped_column(REF)


class AgentIdentityRow(Base):
    """An agent's durable identity within a project.

    One row per `(project, role)`: a project has exactly one Master, and a
    worker's authority comes from its frozen contract rather than from a
    persistent identity, so workers do not accumulate identities across tasks.
    """

    __tablename__ = "agent_identities"
    __table_args__ = (
        UniqueConstraint("project_id", "role", name="uq_agent_identities_one_per_role"),
        _enum_constraint("role", AgentRole),
    )

    identity_id: Mapped[str] = mapped_column(ID, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    role: Mapped[str] = mapped_column(String(32), nullable=False)
    display_name: Mapped[str] = mapped_column(String(128), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    last_seen_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    is_retired: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)


class MasterCheckpointRow(Base):
    """What Master was thinking, written where a recovery can read it.

    A history rather than a single row: the sequence of checkpoints shows how
    Master's understanding moved, and the newest one is a query, not an update.
    """

    __tablename__ = "master_checkpoints"
    __table_args__ = (
        Index("ix_master_checkpoints_project_seq", "project_id", "last_event_seq"),
    )

    checkpoint_id: Mapped[str] = mapped_column(ID, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    master_identity_id: Mapped[str] = mapped_column(REF, nullable=False)
    current_focus: Mapped[str] = mapped_column(Text, nullable=False, default="")
    active_hypotheses: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    pending_questions: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    waiting_on: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    recent_decision_refs: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    important_context_refs: Mapped[list[str]] = mapped_column(
        JSONB, nullable=False, default=list
    )
    last_event_seq: Mapped[int] = mapped_column(BigInteger, nullable=False, default=0)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class ApprovalRequestRow(Base):
    """A question RAVEL is asking a human before it proceeds."""

    __tablename__ = "approval_requests"
    __table_args__ = (
        _enum_constraint("status", ApprovalStatus),
        _enum_constraint("required_role", UserRole),
        CheckConstraint(
            "(status = 'PENDING') = (resolved_at IS NULL)",
            name="resolution_matches_status",
        ),
        Index("ix_approval_requests_project_status", "project_id", "status"),
    )

    approval_id: Mapped[str] = mapped_column(ID, primary_key=True)
    display_id: Mapped[str] = mapped_column(DISPLAY_ID, nullable=False, unique=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    requested_by: Mapped[str] = mapped_column(REF, nullable=False)
    action: Mapped[str] = mapped_column(String(128), nullable=False)
    rationale: Mapped[str] = mapped_column(Text, nullable=False, default="")
    payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    required_role: Mapped[str] = mapped_column(String(32), nullable=False)
    requested_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    resolved_by: Mapped[str | None] = mapped_column(REF)
    resolution_note: Mapped[str] = mapped_column(Text, nullable=False, default="")
    decision_ref: Mapped[str | None] = mapped_column(REF)


class RoadmapPhaseRow(Base):
    """A broad future phase. Only the near ones become executable nodes.

    `order` and `name` are both unique per project. Order is how the roadmap is
    read; the name is how a node refers to its phase, so a duplicate name would
    make `DagNode.roadmap_phase` ambiguous and the planning horizon undefined.
    """

    __tablename__ = "roadmap_phases"
    __table_args__ = (
        UniqueConstraint("project_id", "order", name="uq_roadmap_phases_order"),
        UniqueConstraint("project_id", "name", name="uq_roadmap_phases_name"),
    )

    phase_id: Mapped[str] = mapped_column(ID, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(Text, nullable=False)
    intent: Mapped[str] = mapped_column(Text, nullable=False, default="")
    order: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


# ── Contracts ───────────────────────────────────────────────────────────────


class ResearchContractRow(Base):
    """The original user goal, translated into a scientific problem.

    Append-only. A change to what the user wants is a new contract, never an
    edit to this one, or the record of what RAVEL was asked to do would follow
    what it ended up doing.
    """

    __tablename__ = "research_contracts"

    contract_id: Mapped[str] = mapped_column(ID, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False, unique=True
    )
    original_user_goal: Mapped[str] = mapped_column(Text, nullable=False)
    business_context: Mapped[str] = mapped_column(Text, nullable=False, default="")
    scientific_problem: Mapped[str] = mapped_column(Text, nullable=False)
    research_hypotheses: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    target_metrics: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    acceptance_strategy: Mapped[str] = mapped_column(Text, nullable=False, default="")
    known_constraints: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    assumed_constraints: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    available_resources: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    prohibited_actions: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    budget_time_limits: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, default=dict
    )
    uncertainties: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    authority_envelope_ref: Mapped[str | None] = mapped_column(REF)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class ProjectSuccessContractRow(Base):
    """What project success and failure mean, frozen before formal execution."""

    __tablename__ = "project_success_contracts"
    __table_args__ = (
        UniqueConstraint("project_id", "version", name="uq_project_success_contracts_version"),
    )

    contract_id: Mapped[str] = mapped_column(ID, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    version: Mapped[int] = mapped_column(Integer, nullable=False)
    success_criteria: Mapped[list[str]] = mapped_column(JSONB, nullable=False)
    failure_criteria: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    termination_criteria: Mapped[list[str]] = mapped_column(
        JSONB, nullable=False, default=list
    )
    budget_time_limits: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, default=dict
    )
    unresolved_uncertainty_policy: Mapped[str] = mapped_column(
        Text, nullable=False, default=""
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    supersedes: Mapped[str | None] = mapped_column(REF)
    decision_ref: Mapped[str | None] = mapped_column(REF)


class AuthorityEnvelopeRow(Base):
    """What Master may decide alone, and what needs a human."""

    __tablename__ = "authority_envelopes"
    __table_args__ = (
        UniqueConstraint("project_id", "version", name="uq_authority_envelopes_version"),
    )

    envelope_id: Mapped[str] = mapped_column(ID, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    version: Mapped[int] = mapped_column(Integer, nullable=False)
    requires_approval: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB, nullable=False, default=list
    )
    max_dag_nodes_without_approval: Mapped[int | None] = mapped_column(Integer)
    max_parallel_branches_without_approval: Mapped[int | None] = mapped_column(Integer)
    budget_time_limits: Mapped[dict[str, Any]] = mapped_column(
        JSONB, nullable=False, default=dict
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


# ── The Scientific DAG ──────────────────────────────────────────────────────


class DagNodeRow(Base):
    """One unit of research work.

    The lifecycle columns move; everything else is guarded as immutable by
    `ravel.state.guards`, both for the transition table and for the columns
    that make up the node's identity.
    """

    __tablename__ = "dag_nodes"
    __table_args__ = (
        _enum_constraint("node_type", NodeType),
        _enum_constraint("status", NodeStatus),
        _enum_constraint("executor_role", AgentRole, "executor_role_is_known"),
        _enum_constraint("join_policy", JoinPolicy, "join_policy_is_known"),
        _enum_constraint("failure_policy", FailurePolicy, "failure_policy_is_known"),
        CheckConstraint(
            "(dependencies = '[]'::jsonb AND join_policy IS NULL) "
            "OR (dependencies <> '[]'::jsonb AND join_policy IS NOT NULL)",
            name="join_policy_matches_dependencies",
        ),
        CheckConstraint(
            "join_threshold IS NULL OR join_threshold >= 1",
            name="join_threshold_is_positive",
        ),
        # A node that finished must say when. Without this, a raw UPDATE that
        # set PASSED would leave a node whose place in the timeline cannot be
        # reconstructed — the transition guard would have permitted it, because
        # the move is legal; it is the stamping that was skipped.
        CheckConstraint(
            "(status IN ('PASSED', 'FAILED', 'PARTIAL')) = (completed_at IS NOT NULL)",
            name="completion_time_matches_status",
        ),
        # Every status that implies work started requires a start time.
        CheckConstraint(
            "status NOT IN ('RUNNING', 'WAITING_EXTERNAL', 'WAITING_DECISION', "
            "'REVIEWING', 'PASSED', 'FAILED', 'PARTIAL') OR started_at IS NOT NULL",
            name="started_nodes_have_a_start_time",
        ),
        Index("ix_dag_nodes_project_status", "project_id", "status"),
        Index("ix_dag_nodes_project_type", "project_id", "node_type"),
    )

    node_id: Mapped[str] = mapped_column(ID, primary_key=True)
    display_id: Mapped[str] = mapped_column(DISPLAY_ID, nullable=False, unique=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    node_type: Mapped[str] = mapped_column(String(32), nullable=False)
    objective: Mapped[str] = mapped_column(Text, nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    executor_role: Mapped[str] = mapped_column(String(32), nullable=False)
    dependencies: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    join_policy: Mapped[str | None] = mapped_column(String(32))
    join_threshold: Mapped[int | None] = mapped_column(Integer)
    failure_policy: Mapped[str | None] = mapped_column(String(32))
    acceptance_contract_ref: Mapped[str | None] = mapped_column(REF)
    execution_contract_ref: Mapped[str | None] = mapped_column(REF)
    artifact_refs: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    decision_ref: Mapped[str | None] = mapped_column(REF)
    roadmap_phase: Mapped[str | None] = mapped_column(String(128))
    created_by: Mapped[str] = mapped_column(REF, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class DagEdgeRow(Base):
    """A dependency edge, held as its own auditable fact."""

    __tablename__ = "dag_edges"
    __table_args__ = (
        UniqueConstraint("from_node", "to_node", name="uq_dag_edges_pair"),
        CheckConstraint("from_node <> to_node", name="no_self_edge"),
        Index("ix_dag_edges_project_id", "project_id"),
    )

    edge_id: Mapped[str] = mapped_column(ID, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    from_node: Mapped[str] = mapped_column(
        ID, ForeignKey("dag_nodes.node_id", ondelete="CASCADE"), nullable=False
    )
    to_node: Mapped[str] = mapped_column(
        ID, ForeignKey("dag_nodes.node_id", ondelete="CASCADE"), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class AcceptanceContractRow(Base):
    """Frozen success criteria for one COMPUTATION/EXPERIMENT node."""

    __tablename__ = "acceptance_contracts"
    __table_args__ = (
        UniqueConstraint("node_id", "version", name="uq_acceptance_contracts_version"),
        CheckConstraint("version >= 1", name="version_is_positive"),
    )

    contract_id: Mapped[str] = mapped_column(ID, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    node_id: Mapped[str] = mapped_column(
        ID, ForeignKey("dag_nodes.node_id", ondelete="CASCADE"), nullable=False
    )
    version: Mapped[int] = mapped_column(Integer, nullable=False)
    criteria: Mapped[list[dict[str, Any]]] = mapped_column(JSONB, nullable=False)
    frozen_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    supersedes: Mapped[str | None] = mapped_column(REF)
    decision_ref: Mapped[str | None] = mapped_column(REF)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class ExecutionContractRow(Base):
    """What one Worker is permitted to do for one node."""

    __tablename__ = "execution_contracts"
    __table_args__ = (
        UniqueConstraint("node_id", "version", name="uq_execution_contracts_version"),
        CheckConstraint("version >= 1", name="version_is_positive"),
        CheckConstraint("allowed_retries >= 0", name="retries_are_not_negative"),
    )

    contract_id: Mapped[str] = mapped_column(ID, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    node_id: Mapped[str] = mapped_column(
        ID, ForeignKey("dag_nodes.node_id", ondelete="CASCADE"), nullable=False
    )
    version: Mapped[int] = mapped_column(Integer, nullable=False)
    objective: Mapped[str] = mapped_column(Text, nullable=False)
    procedure: Mapped[str] = mapped_column(Text, nullable=False, default="")
    inputs: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    allowed_actions: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    parameter_targets: Mapped[dict[str, str]] = mapped_column(
        JSONB, nullable=False, default=dict
    )
    allowed_ranges: Mapped[dict[str, str]] = mapped_column(
        JSONB, nullable=False, default=dict
    )
    allowed_retries: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    allowed_substitutions: Mapped[list[str]] = mapped_column(
        JSONB, nullable=False, default=list
    )
    required_outputs: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    stop_conditions: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    escalation_conditions: Mapped[list[str]] = mapped_column(
        JSONB, nullable=False, default=list
    )
    resource_limits: Mapped[dict[str, str]] = mapped_column(
        JSONB, nullable=False, default=dict
    )
    acceptance_contract_ref: Mapped[str | None] = mapped_column(REF)
    frozen_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


# ── Research: sources, evidence, artifacts ──────────────────────────────────


class EvidenceSourceRow(Base):
    """One place a claim came from, as it was actually reached."""

    __tablename__ = "evidence_sources"
    __table_args__ = (
        _enum_constraint("access_status", AccessStatus),
        # The check that matters: only a source that was read may carry a hash
        # or a retrieval time. A restricted source with a hash would assert
        # RAVEL read bytes it could not reach.
        CheckConstraint(
            "(access_status = 'OK') = (retrieved_at IS NOT NULL)",
            name="retrieval_matches_access_status",
        ),
        CheckConstraint(
            "access_status = 'OK' OR content_hash IS NULL",
            name="unread_sources_have_no_hash",
        ),
        Index("ix_evidence_sources_project_url", "project_id", "url"),
    )

    source_id: Mapped[str] = mapped_column(ID, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    url: Mapped[str] = mapped_column(Text, nullable=False)
    title: Mapped[str] = mapped_column(Text, nullable=False, default="")
    publisher: Mapped[str] = mapped_column(Text, nullable=False, default="")
    doi: Mapped[str | None] = mapped_column(String(255))
    access_status: Mapped[str] = mapped_column(String(32), nullable=False)
    retrieved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    content_hash: Mapped[str | None] = mapped_column(String(128))
    media_type: Mapped[str | None] = mapped_column(String(128))
    artifact_ref: Mapped[str | None] = mapped_column(REF)
    #: The object-store key of the stored copy, which is a path and not an
    #: identifier: it is built from the project, the artifact and the version,
    #: so it is longer than `REF` and grows with the length of a filename. Typed
    #: as text to match `ArtifactVersionRow.storage_key`, which holds the same
    #: string for the same object.
    snapshot_ref: Mapped[str | None] = mapped_column(Text)
    notes: Mapped[str] = mapped_column(Text, nullable=False, default="")


class EvidenceRow(Base):
    """One claim, its class, and what supports it."""

    __tablename__ = "evidence"
    __table_args__ = (
        _enum_constraint("claim_class", ClaimClass),
        _enum_constraint("source_tier", EvidenceSourceTier),
        _enum_constraint("access_status", AccessStatus),
        _enum_constraint("confidence", Confidence),
        # A FACT rests on a source that was read. Without this, an unsupported
        # assertion could be recorded as an observation.
        CheckConstraint(
            "claim_class <> 'FACT' OR (source_refs <> '[]'::jsonb AND access_status = 'OK')",
            name="facts_rest_on_readable_sources",
        ),
        Index("ix_evidence_project_claim_class", "project_id", "claim_class"),
    )

    evidence_id: Mapped[str] = mapped_column(ID, primary_key=True)
    display_id: Mapped[str] = mapped_column(DISPLAY_ID, nullable=False, unique=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    statement: Mapped[str] = mapped_column(Text, nullable=False)
    claim_class: Mapped[str] = mapped_column(String(32), nullable=False)
    source_tier: Mapped[str] = mapped_column(String(32), nullable=False)
    source_refs: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    conditions: Mapped[dict[str, str]] = mapped_column(JSONB, nullable=False, default=dict)
    retrieved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    content_hash: Mapped[str | None] = mapped_column(String(128))
    access_status: Mapped[str] = mapped_column(String(32), nullable=False)
    conflicts_with: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    confidence: Mapped[str] = mapped_column(String(32), nullable=False)
    research_task_ref: Mapped[str | None] = mapped_column(REF)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class EvidenceConflictRow(Base):
    """Two evidence rows that disagree, recorded rather than averaged away."""

    __tablename__ = "evidence_conflicts"
    __table_args__ = (
        CheckConstraint("jsonb_array_length(evidence_refs) >= 2", name="a_conflict_needs_two"),
    )

    conflict_id: Mapped[str] = mapped_column(ID, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    evidence_refs: Mapped[list[str]] = mapped_column(JSONB, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    resolution: Mapped[str | None] = mapped_column(Text)
    resolved_by_decision_ref: Mapped[str | None] = mapped_column(REF)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class ResearchRecordRow(Base):
    """A Research Agent's structured output for one task."""

    __tablename__ = "research_records"
    __table_args__ = (
        _enum_constraint("completion_status", CompletionStatus),
        CheckConstraint(
            "completion_status <> 'COMPLETE' OR evidence_refs <> '[]'::jsonb",
            name="complete_research_cites_evidence",
        ),
        Index("ix_research_records_project_task", "project_id", "task_id"),
    )

    research_id: Mapped[str] = mapped_column(ID, primary_key=True)
    display_id: Mapped[str] = mapped_column(DISPLAY_ID, nullable=False, unique=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    task_id: Mapped[str] = mapped_column(REF, nullable=False)
    node_id: Mapped[str | None] = mapped_column(
        ID, ForeignKey("dag_nodes.node_id", ondelete="SET NULL")
    )
    question: Mapped[str] = mapped_column(Text, nullable=False, default="")
    facts: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    inferences: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    hypotheses: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    evidence_refs: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    conflicts: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    sufficiency: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    suggested_acceptance_criteria: Mapped[list[str]] = mapped_column(
        JSONB, nullable=False, default=list
    )
    recommended_followups: Mapped[list[str]] = mapped_column(
        JSONB, nullable=False, default=list
    )
    unknowns: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    completion_status: Mapped[str] = mapped_column(String(32), nullable=False)
    report: Mapped[str] = mapped_column(Text, nullable=False, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class ArtifactRow(Base):
    """A logical artifact, whose versions accumulate.

    Holds metadata only. The bytes are in S3-compatible storage under a key
    derived from the artifact identity and the version number.
    """

    __tablename__ = "artifacts"
    __table_args__ = (Index("ix_artifacts_project_id", "project_id"),)

    artifact_id: Mapped[str] = mapped_column(ID, primary_key=True)
    display_id: Mapped[str] = mapped_column(DISPLAY_ID, nullable=False, unique=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(Text, nullable=False)
    kind: Mapped[str] = mapped_column(String(64), nullable=False, default="")
    media_type: Mapped[str] = mapped_column(String(128), nullable=False, default="")
    provenance: Mapped[str] = mapped_column(Text, nullable=False, default="")
    node_id: Mapped[str | None] = mapped_column(
        ID, ForeignKey("dag_nodes.node_id", ondelete="SET NULL")
    )
    created_by: Mapped[str] = mapped_column(REF, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class ArtifactVersionRow(Base):
    """One immutable set of bytes.

    `storage_key` is unique, so two versions cannot point at the same object
    and a version cannot be re-pointed at different bytes: the row is
    append-only, the key is fixed at insert, and the object it names is written
    once.
    """

    __tablename__ = "artifact_versions"
    __table_args__ = (
        UniqueConstraint("artifact_id", "version", name="uq_artifact_versions_number"),
        CheckConstraint("version >= 1", name="version_starts_at_one"),
        CheckConstraint("size_bytes >= 0", name="size_is_not_negative"),
        Index("ix_artifact_versions_project_hash", "project_id", "content_hash"),
    )

    version_id: Mapped[str] = mapped_column(ID, primary_key=True)
    artifact_id: Mapped[str] = mapped_column(
        ID, ForeignKey("artifacts.artifact_id", ondelete="CASCADE"), nullable=False
    )
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    version: Mapped[int] = mapped_column(Integer, nullable=False)
    storage_key: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    content_hash: Mapped[str] = mapped_column(String(128), nullable=False)
    size_bytes: Mapped[int] = mapped_column(BigInteger, nullable=False)
    media_type: Mapped[str] = mapped_column(String(128), nullable=False, default="")
    filename: Mapped[str] = mapped_column(Text, nullable=False, default="")
    created_by: Mapped[str] = mapped_column(REF, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    node_id: Mapped[str | None] = mapped_column(
        ID, ForeignKey("dag_nodes.node_id", ondelete="SET NULL")
    )
    execution_ref: Mapped[str | None] = mapped_column(REF)
    note: Mapped[str] = mapped_column(Text, nullable=False, default="")


# ── Decisions, reviews, execution ───────────────────────────────────────────


class DecisionRecordRow(Base):
    """Why Master changed the plan. Required for every material mutation."""

    __tablename__ = "decision_records"
    __table_args__ = (
        _enum_constraint("decision_type", DecisionType),
        _enum_constraint("confidence", Confidence),
        Index("ix_decision_records_project_created", "project_id", "created_at"),
    )

    decision_id: Mapped[str] = mapped_column(ID, primary_key=True)
    display_id: Mapped[str] = mapped_column(DISPLAY_ID, nullable=False, unique=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    decision_type: Mapped[str] = mapped_column(String(48), nullable=False)
    trigger_refs: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    rationale: Mapped[str] = mapped_column(Text, nullable=False)
    alternatives_considered: Mapped[list[str]] = mapped_column(
        JSONB, nullable=False, default=list
    )
    evidence_refs: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    affected_nodes: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    confidence: Mapped[str] = mapped_column(String(32), nullable=False)
    authority_check: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class ReviewRecordRow(Base):
    """What Review found, against the criteria frozen before the run."""

    __tablename__ = "review_records"
    __table_args__ = (
        _enum_constraint("checkpoint", ReviewCheckpoint),
        _enum_constraint("outcome", ReviewOutcome),
        CheckConstraint(
            "frozen_acceptance_version >= 1", name="frozen_version_is_positive"
        ),
        Index("ix_review_records_node_created", "node_id", "created_at"),
    )

    review_id: Mapped[str] = mapped_column(ID, primary_key=True)
    display_id: Mapped[str] = mapped_column(DISPLAY_ID, nullable=False, unique=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    node_id: Mapped[str] = mapped_column(
        ID, ForeignKey("dag_nodes.node_id", ondelete="CASCADE"), nullable=False
    )
    checkpoint: Mapped[str] = mapped_column(String(32), nullable=False)
    frozen_acceptance_contract_ref: Mapped[str] = mapped_column(REF, nullable=False)
    frozen_acceptance_version: Mapped[int] = mapped_column(Integer, nullable=False)
    outcome: Mapped[str] = mapped_column(String(32), nullable=False)
    criterion_results: Mapped[list[dict[str, Any]]] = mapped_column(
        JSONB, nullable=False, default=list
    )
    diagnosis: Mapped[str] = mapped_column(Text, nullable=False, default="")
    recommendations: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    artifact_refs: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    evidence_refs: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    review_session_ref: Mapped[str | None] = mapped_column(REF)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class ExecutionRecordRow(Base):
    """The immutable record of one execution.

    Delivery completeness is stored beside the termination status, never merged
    into it: a missing artifact is not a scientific failure, and a schema that
    could not tell them apart would send Master hunting for a flaw in a result
    that was never delivered.
    """

    __tablename__ = "execution_records"
    __table_args__ = (
        _enum_constraint("termination_status", TerminationStatus),
        CheckConstraint(
            "execution_contract_version >= 1", name="contract_version_is_positive"
        ),
        Index("ix_execution_records_node_created", "node_id", "created_at"),
    )

    execution_id: Mapped[str] = mapped_column(ID, primary_key=True)
    display_id: Mapped[str] = mapped_column(DISPLAY_ID, nullable=False, unique=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    node_id: Mapped[str] = mapped_column(
        ID, ForeignKey("dag_nodes.node_id", ondelete="CASCADE"), nullable=False
    )
    execution_contract_ref: Mapped[str] = mapped_column(REF, nullable=False)
    execution_contract_version: Mapped[int] = mapped_column(Integer, nullable=False)
    backend: Mapped[str] = mapped_column(String(64), nullable=False)
    backend_job_ref: Mapped[str | None] = mapped_column(REF)
    attempts: Mapped[list[dict[str, Any]]] = mapped_column(JSONB, nullable=False, default=list)
    output_refs: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    log_refs: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    completeness: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False)
    deviations: Mapped[list[str]] = mapped_column(JSONB, nullable=False, default=list)
    termination_status: Mapped[str] = mapped_column(String(32), nullable=False)
    executed_by: Mapped[str] = mapped_column(REF, nullable=False, default="")
    started_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class DeviationRecordRow(Base):
    """Something asked for that the Execution Contract did not permit."""

    __tablename__ = "deviation_records"
    __table_args__ = (
        CheckConstraint(
            "(resolved_by_decision_ref IS NULL) = (resolved_at IS NULL)",
            name="resolution_is_all_or_nothing",
        ),
        Index("ix_deviation_records_node_open", "node_id", "resolved_by_decision_ref"),
    )

    deviation_id: Mapped[str] = mapped_column(ID, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    node_id: Mapped[str] = mapped_column(
        ID, ForeignKey("dag_nodes.node_id", ondelete="CASCADE"), nullable=False
    )
    execution_contract_ref: Mapped[str] = mapped_column(REF, nullable=False)
    requested_action: Mapped[str] = mapped_column(String(128), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    permitted: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    raised_by: Mapped[str] = mapped_column(REF, nullable=False)
    raised_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    resolved_by_decision_ref: Mapped[str | None] = mapped_column(REF)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


#: The terminal job states, as SQL literals, derived from the enum so a state
#: added there cannot leave this constraint behind.
_TERMINAL_JOB_STATES_SQL = ", ".join(
    f"'{state.value}'" for state in JobState if state.is_terminal
)

#: The states a failure class may appear in. Deliberately narrower than the
#: terminal set: a job that was cancelled, or that succeeded, did not fail, and
#: the class is what decides whether work runs again.
_FAILED_JOB_STATES_SQL = ", ".join(
    f"'{state.value}'" for state in (JobState.FAILED, JobState.TIMED_OUT)
)


class BackendJobRow(Base):
    """A job handed to a compute or experiment backend, while it is in flight.

    Two constraints here are doing load-bearing work rather than describing the
    data.

    `one_job_per_attempt` is what makes starting a job idempotent. A worker
    that dies between the backend accepting the work and the result being
    recorded is retried, and the retry must find the job it already started
    rather than start a second one. Because the uniqueness is enforced by the
    database, the guarantee holds for a retry that races the original — two
    activities that both try to insert get one row and one conflict, never two
    rows.

    `failure_class_only_on_failure` is what keeps the retry policy honest. The
    class is what decides whether work runs again, so a class left on a job
    that succeeded is a reason to repeat an experiment that already produced a
    result.
    """

    __tablename__ = "backend_jobs"
    __table_args__ = (
        _enum_constraint("state", JobState),
        _enum_constraint("failure_class", FailureClass),
        CheckConstraint("attempt >= 1", name="attempt_is_positive"),
        CheckConstraint(
            "execution_contract_version >= 1", name="contract_version_is_positive"
        ),
        CheckConstraint(
            f"(state IN ({_TERMINAL_JOB_STATES_SQL})) = (ended_at IS NOT NULL)",
            name="ending_is_all_or_nothing",
        ),
        CheckConstraint(
            f"failure_class IS NULL OR state IN ({_FAILED_JOB_STATES_SQL})",
            name="failure_class_only_on_failure",
        ),
        UniqueConstraint(
            "project_id", "node_id", "attempt", name="one_job_per_attempt"
        ),
        Index("ix_backend_jobs_node_state", "node_id", "state"),
    )

    job_id: Mapped[str] = mapped_column(ID, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    node_id: Mapped[str] = mapped_column(
        ID, ForeignKey("dag_nodes.node_id", ondelete="CASCADE"), nullable=False
    )
    attempt: Mapped[int] = mapped_column(Integer, nullable=False)
    execution_contract_ref: Mapped[str] = mapped_column(REF, nullable=False)
    execution_contract_version: Mapped[int] = mapped_column(Integer, nullable=False)
    backend: Mapped[str] = mapped_column(String(64), nullable=False)
    backend_job_ref: Mapped[str | None] = mapped_column(REF)
    state: Mapped[str] = mapped_column(String(32), nullable=False)
    backend_state: Mapped[str] = mapped_column(String(64), nullable=False, default="")
    failure_class: Mapped[str | None] = mapped_column(String(32))
    detail: Mapped[str] = mapped_column(Text, nullable=False, default="")
    submitted_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    ended_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class WorkerMessageRow(Base):
    """Something a Worker said, inside the four permitted kinds."""

    __tablename__ = "worker_messages"
    __table_args__ = (
        _enum_constraint("kind", WorkerMessageKind),
        Index("ix_worker_messages_node_sent", "node_id", "sent_at"),
    )

    message_id: Mapped[str] = mapped_column(ID, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    node_id: Mapped[str] = mapped_column(
        ID, ForeignKey("dag_nodes.node_id", ondelete="CASCADE"), nullable=False
    )
    kind: Mapped[str] = mapped_column(String(32), nullable=False)
    body: Mapped[str] = mapped_column(Text, nullable=False)
    approved_by_contract: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    sent_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


# ── The event stream ────────────────────────────────────────────────────────


class ProjectEventRow(Base):
    """One entry in a project's stream.

    `seq` is contiguous per project and assigned by `project_event_counters`,
    which takes a row lock. A consumer that sees a gap knows it missed
    something; a sequence with holes would make that signal meaningless.
    """

    __tablename__ = "project_events"
    __table_args__ = (
        UniqueConstraint("project_id", "seq", name="uq_project_events_seq"),
        _enum_constraint("event_type", ProjectEventType),
        _enum_constraint("actor_type", ActorType),
        CheckConstraint("seq >= 1", name="seq_starts_at_one"),
        Index("ix_project_events_project_created", "project_id", "created_at"),
    )

    event_id: Mapped[str] = mapped_column(ID, primary_key=True)
    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), nullable=False
    )
    seq: Mapped[int] = mapped_column(BigInteger, nullable=False)
    event_type: Mapped[str] = mapped_column(String(48), nullable=False)
    actor_type: Mapped[str] = mapped_column(String(16), nullable=False)
    actor_id: Mapped[str] = mapped_column(REF, nullable=False)
    payload: Mapped[dict[str, Any]] = mapped_column(JSONB, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)


class ProjectEventCounterRow(Base):
    """The next sequence number for one project.

    A counter row rather than `MAX(seq) + 1` because the counter is what makes
    the sequence gap-free under concurrency: the `UPDATE ... RETURNING` takes a
    row lock, so two writers to the same project serialize, and a rollback
    returns the number it took.
    """

    __tablename__ = "project_event_counters"

    project_id: Mapped[str] = mapped_column(
        ID, ForeignKey("projects.project_id", ondelete="CASCADE"), primary_key=True
    )
    next_seq: Mapped[int] = mapped_column(BigInteger, nullable=False, default=1)


def _install_guards(_target: Any, connection: Any, **_: Any) -> None:
    """Attach the DDL guards whenever the metadata creates its tables.

    Deferred import: `guards` reads this module's metadata, so importing it at
    module scope would be circular.
    """
    from ravel.state import guards

    guards.install(connection)


# `after_create` fires once per `metadata.create_all()`, after every table
# exists, which is the earliest point the triggers can be attached.
event.listen(Base.metadata, "after_create", _install_guards)
