"""initial schema

Revision ID: 5c2355f96e2a
Revises: 
Created: 2026-09-19 05:56:26.577958
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '5c2355f96e2a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('display_id', sa.String(length=40), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paused_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('CREATED', 'CONTRACT_DEFINED', 'EXECUTING', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED')", name=op.f('ck_projects_status_is_known')),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_projects')),
    sa.UniqueConstraint('display_id', name=op.f('uq_projects_display_id'))
    )
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('agent_identities',
    sa.Column('identity_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_retired', sa.Boolean(), nullable=False),
    sa.CheckConstraint("role IN ('master', 'research', 'review', 'compute-worker', 'experimental-worker')", name=op.f('ck_agent_identities_role_is_known')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_agent_identities_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('identity_id', name=op.f('pk_agent_identities')),
    sa.UniqueConstraint('project_id', 'role', name='uq_agent_identities_one_per_role')
    )
    op.create_table('approval_requests',
    sa.Column('approval_id', sa.String(length=32), nullable=False),
    sa.Column('display_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('required_role', sa.String(length=32), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=False),
    sa.Column('decision_ref', sa.String(length=64), nullable=True),
    sa.CheckConstraint("(status = 'PENDING') = (resolved_at IS NULL)", name=op.f('ck_approval_requests_resolution_matches_status')),
    sa.CheckConstraint("required_role IN ('PROJECT_OWNER', 'LAB_USER', 'ADMIN')", name=op.f('ck_approval_requests_required_role_is_known')),
    sa.CheckConstraint("status IN ('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED')", name=op.f('ck_approval_requests_status_is_known')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_approval_requests_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('approval_id', name=op.f('pk_approval_requests')),
    sa.UniqueConstraint('display_id', name=op.f('uq_approval_requests_display_id'))
    )
    op.create_index('ix_approval_requests_project_status', 'approval_requests', ['project_id', 'status'], unique=False)
    op.create_table('authority_envelopes',
    sa.Column('envelope_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('requires_approval', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_dag_nodes_without_approval', sa.Integer(), nullable=True),
    sa.Column('max_parallel_branches_without_approval', sa.Integer(), nullable=True),
    sa.Column('budget_time_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_authority_envelopes_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('envelope_id', name=op.f('pk_authority_envelopes')),
    sa.UniqueConstraint('project_id', 'version', name='uq_authority_envelopes_version')
    )
    op.create_table('dag_nodes',
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('display_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('executor_role', sa.String(length=32), nullable=False),
    sa.Column('dependencies', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('join_policy', sa.String(length=32), nullable=True),
    sa.Column('join_threshold', sa.Integer(), nullable=True),
    sa.Column('failure_policy', sa.String(length=32), nullable=True),
    sa.Column('acceptance_contract_ref', sa.String(length=64), nullable=True),
    sa.Column('execution_contract_ref', sa.String(length=64), nullable=True),
    sa.Column('artifact_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision_ref', sa.String(length=64), nullable=True),
    sa.Column('roadmap_phase', sa.String(length=128), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(dependencies = '[]'::jsonb AND join_policy IS NULL) OR (dependencies <> '[]'::jsonb AND join_policy IS NOT NULL)", name=op.f('ck_dag_nodes_join_policy_matches_dependencies')),
    sa.CheckConstraint("(status IN ('PASSED', 'FAILED', 'PARTIAL')) = (completed_at IS NOT NULL)", name=op.f('ck_dag_nodes_completion_time_matches_status')),
    sa.CheckConstraint("executor_role IN ('master', 'research', 'review', 'compute-worker', 'experimental-worker')", name=op.f('ck_dag_nodes_executor_role_is_known')),
    sa.CheckConstraint("failure_policy IN ('BLOCK', 'CONTINUE', 'MASTER_DECIDES')", name=op.f('ck_dag_nodes_failure_policy_is_known')),
    sa.CheckConstraint("join_policy IN ('ALL', 'ANY', 'THRESHOLD')", name=op.f('ck_dag_nodes_join_policy_is_known')),
    sa.CheckConstraint("node_type IN ('RESEARCH', 'HYPOTHESIS', 'COMPUTATION', 'EXPERIMENT', 'REVIEW', 'DECISION')", name=op.f('ck_dag_nodes_node_type_is_known')),
    sa.CheckConstraint("status IN ('PLANNED', 'READY', 'RUNNING', 'WAITING_EXTERNAL', 'WAITING_DECISION', 'REVIEWING', 'PASSED', 'FAILED', 'PARTIAL', 'BLOCKED', 'CANCELLED')", name=op.f('ck_dag_nodes_status_is_known')),
    sa.CheckConstraint("status NOT IN ('RUNNING', 'WAITING_EXTERNAL', 'WAITING_DECISION', 'REVIEWING', 'PASSED', 'FAILED', 'PARTIAL') OR started_at IS NOT NULL", name=op.f('ck_dag_nodes_started_nodes_have_a_start_time')),
    sa.CheckConstraint('join_threshold IS NULL OR join_threshold >= 1', name=op.f('ck_dag_nodes_join_threshold_is_positive')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_dag_nodes_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id', name=op.f('pk_dag_nodes')),
    sa.UniqueConstraint('display_id', name=op.f('uq_dag_nodes_display_id'))
    )
    op.create_index('ix_dag_nodes_project_status', 'dag_nodes', ['project_id', 'status'], unique=False)
    op.create_index('ix_dag_nodes_project_type', 'dag_nodes', ['project_id', 'node_type'], unique=False)
    op.create_table('decision_records',
    sa.Column('decision_id', sa.String(length=32), nullable=False),
    sa.Column('display_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('decision_type', sa.String(length=48), nullable=False),
    sa.Column('trigger_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('alternatives_considered', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('affected_nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.Column('authority_check', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("confidence IN ('LOW', 'MEDIUM', 'HIGH')", name=op.f('ck_decision_records_confidence_is_known')),
    sa.CheckConstraint("decision_type IN ('CREATE_NODE', 'CANCEL_NODE', 'REPLACE_NODE', 'REVISE_EXECUTION_CONTRACT', 'REVISE_ACCEPTANCE_CRITERIA', 'CHANGE_ROUTE', 'RESOLVE_DEVIATION', 'ACCEPT_RESULT', 'REJECT_RESULT', 'TERMINATE_PROJECT', 'RESOLVE_APPROVAL')", name=op.f('ck_decision_records_decision_type_is_known')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_decision_records_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('decision_id', name=op.f('pk_decision_records')),
    sa.UniqueConstraint('display_id', name=op.f('uq_decision_records_display_id'))
    )
    op.create_index('ix_decision_records_project_created', 'decision_records', ['project_id', 'created_at'], unique=False)
    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(length=32), nullable=False),
    sa.Column('display_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('claim_class', sa.String(length=32), nullable=False),
    sa.Column('source_tier', sa.String(length=32), nullable=False),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('access_status', sa.String(length=32), nullable=False),
    sa.Column('conflicts_with', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.String(length=32), nullable=False),
    sa.Column('research_task_ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("access_status IN ('OK', 'PAYWALLED', 'AUTH_REQUIRED', 'ACCESS_LIMITED', 'POLICY_BLOCKED')", name=op.f('ck_evidence_access_status_is_known')),
    sa.CheckConstraint("claim_class <> 'FACT' OR (source_refs <> '[]'::jsonb AND access_status = 'OK')", name=op.f('ck_evidence_facts_rest_on_readable_sources')),
    sa.CheckConstraint("claim_class IN ('FACT', 'INFERENCE', 'HYPOTHESIS')", name=op.f('ck_evidence_claim_class_is_known')),
    sa.CheckConstraint("confidence IN ('LOW', 'MEDIUM', 'HIGH')", name=op.f('ck_evidence_confidence_is_known')),
    sa.CheckConstraint("source_tier IN ('A', 'B', 'C', 'D')", name=op.f('ck_evidence_source_tier_is_known')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_evidence_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('evidence_id', name=op.f('pk_evidence')),
    sa.UniqueConstraint('display_id', name=op.f('uq_evidence_display_id'))
    )
    op.create_index('ix_evidence_project_claim_class', 'evidence', ['project_id', 'claim_class'], unique=False)
    op.create_table('evidence_conflicts',
    sa.Column('conflict_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_by_decision_ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('jsonb_array_length(evidence_refs) >= 2', name=op.f('ck_evidence_conflicts_a_conflict_needs_two')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_evidence_conflicts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conflict_id', name=op.f('pk_evidence_conflicts'))
    )
    op.create_table('evidence_sources',
    sa.Column('source_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('publisher', sa.Text(), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('access_status', sa.String(length=32), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('media_type', sa.String(length=128), nullable=True),
    sa.Column('artifact_ref', sa.String(length=64), nullable=True),
    sa.Column('snapshot_ref', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.CheckConstraint("(access_status = 'OK') = (retrieved_at IS NOT NULL)", name=op.f('ck_evidence_sources_retrieval_matches_access_status')),
    sa.CheckConstraint("access_status = 'OK' OR content_hash IS NULL", name=op.f('ck_evidence_sources_unread_sources_have_no_hash')),
    sa.CheckConstraint("access_status IN ('OK', 'PAYWALLED', 'AUTH_REQUIRED', 'ACCESS_LIMITED', 'POLICY_BLOCKED')", name=op.f('ck_evidence_sources_access_status_is_known')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_evidence_sources_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', name=op.f('pk_evidence_sources'))
    )
    op.create_index('ix_evidence_sources_project_url', 'evidence_sources', ['project_id', 'url'], unique=False)
    op.create_table('master_checkpoints',
    sa.Column('checkpoint_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('master_identity_id', sa.String(length=64), nullable=False),
    sa.Column('current_focus', sa.Text(), nullable=False),
    sa.Column('active_hypotheses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pending_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('waiting_on', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recent_decision_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('important_context_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_event_seq', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_master_checkpoints_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checkpoint_id', name=op.f('pk_master_checkpoints'))
    )
    op.create_index('ix_master_checkpoints_project_seq', 'master_checkpoints', ['project_id', 'last_event_seq'], unique=False)
    op.create_table('project_event_counters',
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('next_seq', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_project_event_counters_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_project_event_counters'))
    )
    op.create_table('project_events',
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("actor_type IN ('USER', 'AGENT', 'SYSTEM', 'BACKEND')", name=op.f('ck_project_events_actor_type_is_known')),
    sa.CheckConstraint("event_type IN ('PROJECT_CREATED', 'PROJECT_STATUS_CHANGED', 'MASTER_STARTED', 'MASTER_CHECKPOINTED', 'MASTER_RECOVERED', 'NODE_CREATED', 'NODE_READY', 'NODE_STARTED', 'NODE_WAITING', 'NODE_COMPLETED', 'NODE_FAILED', 'NODE_CANCELLED', 'REVIEW_SUBMITTED', 'DECISION_CREATED', 'DAG_MUTATED', 'DEVIATION_REPORTED', 'ARTIFACT_REGISTERED', 'EVIDENCE_REGISTERED', 'APPROVAL_REQUESTED', 'APPROVAL_RESOLVED', 'BACKEND_STATUS_CHANGED', 'AGENT_SESSION_STARTED', 'AGENT_SESSION_ENDED')", name=op.f('ck_project_events_event_type_is_known')),
    sa.CheckConstraint('seq >= 1', name=op.f('ck_project_events_seq_starts_at_one')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_project_events_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_project_events')),
    sa.UniqueConstraint('project_id', 'seq', name='uq_project_events_seq')
    )
    op.create_index('ix_project_events_project_created', 'project_events', ['project_id', 'created_at'], unique=False)
    op.create_table('project_memberships',
    sa.Column('membership_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('granted_by', sa.String(length=64), nullable=True),
    sa.CheckConstraint("role IN ('PROJECT_OWNER', 'LAB_USER', 'ADMIN')", name=op.f('ck_project_memberships_role_is_known')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_project_memberships_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_project_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('membership_id', name=op.f('pk_project_memberships')),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_memberships_one_role')
    )
    op.create_index('ix_project_memberships_user_id', 'project_memberships', ['user_id'], unique=False)
    op.create_table('project_success_contracts',
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('success_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failure_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('termination_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('budget_time_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unresolved_uncertainty_policy', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supersedes', sa.String(length=64), nullable=True),
    sa.Column('decision_ref', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_project_success_contracts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contract_id', name=op.f('pk_project_success_contracts')),
    sa.UniqueConstraint('project_id', 'version', name='uq_project_success_contracts_version')
    )
    op.create_table('research_contracts',
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('original_user_goal', sa.Text(), nullable=False),
    sa.Column('business_context', sa.Text(), nullable=False),
    sa.Column('scientific_problem', sa.Text(), nullable=False),
    sa.Column('research_hypotheses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('acceptance_strategy', sa.Text(), nullable=False),
    sa.Column('known_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assumed_constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('available_resources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prohibited_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('budget_time_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uncertainties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('authority_envelope_ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_research_contracts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contract_id', name=op.f('pk_research_contracts')),
    sa.UniqueConstraint('project_id', name=op.f('uq_research_contracts_project_id'))
    )
    op.create_table('roadmap_phases',
    sa.Column('phase_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('intent', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('expanded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_roadmap_phases_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('phase_id', name=op.f('pk_roadmap_phases')),
    sa.UniqueConstraint('project_id', 'order', name='uq_roadmap_phases_order')
    )
    op.create_table('acceptance_contracts',
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes', sa.String(length=64), nullable=True),
    sa.Column('decision_ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version >= 1', name=op.f('ck_acceptance_contracts_version_is_positive')),
    sa.ForeignKeyConstraint(['node_id'], ['dag_nodes.node_id'], name=op.f('fk_acceptance_contracts_node_id_dag_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_acceptance_contracts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contract_id', name=op.f('pk_acceptance_contracts')),
    sa.UniqueConstraint('node_id', 'version', name='uq_acceptance_contracts_version')
    )
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.String(length=32), nullable=False),
    sa.Column('display_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('provenance', sa.Text(), nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['dag_nodes.node_id'], name=op.f('fk_artifacts_node_id_dag_nodes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_artifacts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artifact_id', name=op.f('pk_artifacts')),
    sa.UniqueConstraint('display_id', name=op.f('uq_artifacts_display_id'))
    )
    op.create_index('ix_artifacts_project_id', 'artifacts', ['project_id'], unique=False)
    op.create_table('dag_edges',
    sa.Column('edge_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('from_node', sa.String(length=32), nullable=False),
    sa.Column('to_node', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('from_node <> to_node', name=op.f('ck_dag_edges_no_self_edge')),
    sa.ForeignKeyConstraint(['from_node'], ['dag_nodes.node_id'], name=op.f('fk_dag_edges_from_node_dag_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_dag_edges_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node'], ['dag_nodes.node_id'], name=op.f('fk_dag_edges_to_node_dag_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('edge_id', name=op.f('pk_dag_edges')),
    sa.UniqueConstraint('from_node', 'to_node', name='uq_dag_edges_pair')
    )
    op.create_index('ix_dag_edges_project_id', 'dag_edges', ['project_id'], unique=False)
    op.create_table('deviation_records',
    sa.Column('deviation_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('execution_contract_ref', sa.String(length=64), nullable=False),
    sa.Column('requested_action', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('permitted', sa.Boolean(), nullable=False),
    sa.Column('raised_by', sa.String(length=64), nullable=False),
    sa.Column('raised_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_by_decision_ref', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(resolved_by_decision_ref IS NULL) = (resolved_at IS NULL)', name=op.f('ck_deviation_records_resolution_is_all_or_nothing')),
    sa.ForeignKeyConstraint(['node_id'], ['dag_nodes.node_id'], name=op.f('fk_deviation_records_node_id_dag_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_deviation_records_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('deviation_id', name=op.f('pk_deviation_records'))
    )
    op.create_index('ix_deviation_records_node_open', 'deviation_records', ['node_id', 'resolved_by_decision_ref'], unique=False)
    op.create_table('execution_contracts',
    sa.Column('contract_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('procedure', sa.Text(), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parameter_targets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_ranges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('allowed_retries', sa.Integer(), nullable=False),
    sa.Column('allowed_substitutions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stop_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('escalation_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resource_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('acceptance_contract_ref', sa.String(length=64), nullable=True),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('allowed_retries >= 0', name=op.f('ck_execution_contracts_retries_are_not_negative')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_execution_contracts_version_is_positive')),
    sa.ForeignKeyConstraint(['node_id'], ['dag_nodes.node_id'], name=op.f('fk_execution_contracts_node_id_dag_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_execution_contracts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contract_id', name=op.f('pk_execution_contracts')),
    sa.UniqueConstraint('node_id', 'version', name='uq_execution_contracts_version')
    )
    op.create_table('execution_records',
    sa.Column('execution_id', sa.String(length=32), nullable=False),
    sa.Column('display_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('execution_contract_ref', sa.String(length=64), nullable=False),
    sa.Column('execution_contract_version', sa.Integer(), nullable=False),
    sa.Column('backend', sa.String(length=64), nullable=False),
    sa.Column('backend_job_ref', sa.String(length=64), nullable=True),
    sa.Column('attempts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('log_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completeness', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deviations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('termination_status', sa.String(length=32), nullable=False),
    sa.Column('executed_by', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("termination_status IN ('COMPLETED', 'FAILED', 'CANCELLED', 'TIMED_OUT', 'DEVIATION')", name=op.f('ck_execution_records_termination_status_is_known')),
    sa.CheckConstraint('execution_contract_version >= 1', name=op.f('ck_execution_records_contract_version_is_positive')),
    sa.ForeignKeyConstraint(['node_id'], ['dag_nodes.node_id'], name=op.f('fk_execution_records_node_id_dag_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_execution_records_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('execution_id', name=op.f('pk_execution_records')),
    sa.UniqueConstraint('display_id', name=op.f('uq_execution_records_display_id'))
    )
    op.create_index('ix_execution_records_node_created', 'execution_records', ['node_id', 'created_at'], unique=False)
    op.create_table('research_records',
    sa.Column('research_id', sa.String(length=32), nullable=False),
    sa.Column('display_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=True),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hypotheses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('conflicts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sufficiency', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_acceptance_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_followups', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unknowns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completion_status', sa.String(length=32), nullable=False),
    sa.Column('report', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("completion_status <> 'COMPLETE' OR evidence_refs <> '[]'::jsonb", name=op.f('ck_research_records_complete_research_cites_evidence')),
    sa.CheckConstraint("completion_status IN ('COMPLETE', 'INCOMPLETE')", name=op.f('ck_research_records_completion_status_is_known')),
    sa.ForeignKeyConstraint(['node_id'], ['dag_nodes.node_id'], name=op.f('fk_research_records_node_id_dag_nodes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_research_records_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('research_id', name=op.f('pk_research_records')),
    sa.UniqueConstraint('display_id', name=op.f('uq_research_records_display_id'))
    )
    op.create_index('ix_research_records_project_task', 'research_records', ['project_id', 'task_id'], unique=False)
    op.create_table('review_records',
    sa.Column('review_id', sa.String(length=32), nullable=False),
    sa.Column('display_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('checkpoint', sa.String(length=32), nullable=False),
    sa.Column('frozen_acceptance_contract_ref', sa.String(length=64), nullable=False),
    sa.Column('frozen_acceptance_version', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('criterion_results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('artifact_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('review_session_ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("checkpoint IN ('PRE_RUN', 'RUNTIME', 'FINAL')", name=op.f('ck_review_records_checkpoint_is_known')),
    sa.CheckConstraint("outcome IN ('PASS', 'FAIL', 'PARTIAL')", name=op.f('ck_review_records_outcome_is_known')),
    sa.CheckConstraint('frozen_acceptance_version >= 1', name=op.f('ck_review_records_frozen_version_is_positive')),
    sa.ForeignKeyConstraint(['node_id'], ['dag_nodes.node_id'], name=op.f('fk_review_records_node_id_dag_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_review_records_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id', name=op.f('pk_review_records')),
    sa.UniqueConstraint('display_id', name=op.f('uq_review_records_display_id'))
    )
    op.create_index('ix_review_records_node_created', 'review_records', ['node_id', 'created_at'], unique=False)
    op.create_table('worker_messages',
    sa.Column('message_id', sa.String(length=32), nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('approved_by_contract', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("kind IN ('CONFIRM', 'INFORM', 'REQUEST_MISSING_INFORMATION', 'ESCALATE')", name=op.f('ck_worker_messages_kind_is_known')),
    sa.ForeignKeyConstraint(['node_id'], ['dag_nodes.node_id'], name=op.f('fk_worker_messages_node_id_dag_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', name=op.f('pk_worker_messages'))
    )
    op.create_table('artifact_versions',
    sa.Column('version_id', sa.String(length=32), nullable=False),
    sa.Column('artifact_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('node_id', sa.String(length=32), nullable=True),
    sa.Column('execution_ref', sa.String(length=64), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_artifact_versions_size_is_not_negative')),
    sa.CheckConstraint('version >= 1', name=op.f('ck_artifact_versions_version_starts_at_one')),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.artifact_id'], name=op.f('fk_artifact_versions_artifact_id_artifacts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['dag_nodes.node_id'], name=op.f('fk_artifact_versions_node_id_dag_nodes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_artifact_versions_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('version_id', name=op.f('pk_artifact_versions')),
    sa.UniqueConstraint('artifact_id', 'version', name='uq_artifact_versions_number'),
    sa.UniqueConstraint('storage_key', name=op.f('uq_artifact_versions_storage_key'))
    )
    op.create_index('ix_artifact_versions_project_hash', 'artifact_versions', ['project_id', 'content_hash'], unique=False)
    # ### end Alembic commands ###

    _install_guards()


def _install_guards() -> None:
    """Attach the database-level guards.

    Not part of the autogenerated body because they are not tables: the
    transition lookup tables, the trigger functions, and the triggers
    themselves are owned by `ravel.state.guards`, so the migration, the test
    schema, and a fresh `create_all` all install byte-identical rules.

    Kept out of `alembic revision --autogenerate` by `env.include_object`, so a
    later diff cannot propose dropping and recreating enforcement it does not
    understand.
    """
    from ravel.state import guards

    guards.install(op.get_bind())


def _drop_guards() -> None:
    """Remove the guard objects before the tables they are attached to.

    The triggers belong to their tables and go with them, but the functions and
    the two transition lookup tables do not, and `DROP FUNCTION` refuses while
    any trigger still depends on it — so this runs before the table drops below.

    Delegated to `guards.drop`, which is driven by the same name tuples as
    `guard.install`. A list written out here by hand would drift from the
    install list, and the drift would surface as a dependency error in an
    unrelated downgrade.
    """
    from ravel.state import guards

    guards.drop(op.get_bind())


def downgrade() -> None:
    _drop_guards()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_artifact_versions_project_hash', table_name='artifact_versions')
    op.drop_table('artifact_versions')
    op.drop_table('worker_messages')
    op.drop_index('ix_review_records_node_created', table_name='review_records')
    op.drop_table('review_records')
    op.drop_index('ix_research_records_project_task', table_name='research_records')
    op.drop_table('research_records')
    op.drop_index('ix_execution_records_node_created', table_name='execution_records')
    op.drop_table('execution_records')
    op.drop_table('execution_contracts')
    op.drop_index('ix_deviation_records_node_open', table_name='deviation_records')
    op.drop_table('deviation_records')
    op.drop_index('ix_dag_edges_project_id', table_name='dag_edges')
    op.drop_table('dag_edges')
    op.drop_index('ix_artifacts_project_id', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_table('acceptance_contracts')
    op.drop_table('roadmap_phases')
    op.drop_table('research_contracts')
    op.drop_table('project_success_contracts')
    op.drop_index('ix_project_memberships_user_id', table_name='project_memberships')
    op.drop_table('project_memberships')
    op.drop_index('ix_project_events_project_created', table_name='project_events')
    op.drop_table('project_events')
    op.drop_table('project_event_counters')
    op.drop_index('ix_master_checkpoints_project_seq', table_name='master_checkpoints')
    op.drop_table('master_checkpoints')
    op.drop_index('ix_evidence_sources_project_url', table_name='evidence_sources')
    op.drop_table('evidence_sources')
    op.drop_table('evidence_conflicts')
    op.drop_index('ix_evidence_project_claim_class', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_decision_records_project_created', table_name='decision_records')
    op.drop_table('decision_records')
    op.drop_index('ix_dag_nodes_project_type', table_name='dag_nodes')
    op.drop_index('ix_dag_nodes_project_status', table_name='dag_nodes')
    op.drop_table('dag_nodes')
    op.drop_table('authority_envelopes')
    op.drop_index('ix_approval_requests_project_status', table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_table('agent_identities')
    op.drop_table('users')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
