"""RAVEL's domain model.

Everything here is a value: frozen records, closed vocabularies, and pure
functions over them. Nothing in this package opens a connection, reads the
clock from the environment, or talks to a harness — which is what makes the
rules it encodes testable without any infrastructure running.
"""

from ravel.domain.artifacts import (
    ARTIFACT_KEY_TEMPLATE,
    Artifact,
    ArtifactRegistration,
    ArtifactVersion,
    artifact_key,
)
from ravel.domain.base import Record
from ravel.domain.clock import ensure_utc, utcnow
from ravel.domain.contracts import (
    AcceptanceContract,
    AcceptanceCriterion,
    ApprovalRequirement,
    AuthorityEnvelope,
    BudgetLimits,
    ExecutionContract,
    ProjectSuccessContract,
    ResearchContract,
)
from ravel.domain.dag import DagEdge, DagNode
from ravel.domain.decisions import (
    AffectedNodes,
    AuthorityCheck,
    CriterionResult,
    DecisionRecord,
    ReviewRecord,
)
from ravel.domain.enums import (
    AccessStatus,
    ApprovalStatus,
    ClaimClass,
    CompletenessVerdict,
    CompletionStatus,
    Confidence,
    CriterionProvenance,
    DecisionType,
    EvidenceSourceTier,
    FailurePolicy,
    JoinPolicy,
    NodeStatus,
    NodeType,
    ProjectStatus,
    ReviewCheckpoint,
    ReviewOutcome,
    Sufficiency,
    TerminationStatus,
    UserRole,
    WorkerMessageKind,
)
from ravel.domain.events import ActorType, ProjectEvent, ProjectEventType
from ravel.domain.evidence import (
    Evidence,
    EvidenceConflict,
    EvidenceSource,
    ResearchRecord,
    SufficiencyAssessment,
)
from ravel.domain.execution import (
    CompletenessCheck,
    DeviationRecord,
    ExecutionAttempt,
    ExecutionRecord,
    WorkerMessage,
)
from ravel.domain.identity import (
    AgentIdentity,
    ApprovalRequest,
    MasterCheckpoint,
    ProjectMembership,
    User,
)
from ravel.domain.ids import DisplayPrefix, display_id, is_opaque_id, new_id
from ravel.domain.project import Project, Roadmap, RoadmapPhase
from ravel.domain.roles import AgentRole
from ravel.domain.state_machines import (
    ACTIVE_NODE_STATUSES,
    FROZEN_CRITERIA_NODE_TYPES,
    NODE_EXECUTOR,
    NODE_TRANSITIONS,
    PLANNABLE_NODE_TYPES,
    PROJECT_TRANSITIONS,
    SEATED_NODE_TYPES,
    TERMINAL_NODE_STATUSES,
    TERMINAL_PROJECT_STATUSES,
    WORKER_RUN_NODE_TYPES,
    TransitionCheck,
    TransitionError,
    can_transition_node,
    can_transition_project,
    executor_for,
    is_join_satisfied,
    requires_frozen_criteria,
    unexecutable_reason,
)

__all__ = [
    "ACTIVE_NODE_STATUSES",
    "ARTIFACT_KEY_TEMPLATE",
    "FROZEN_CRITERIA_NODE_TYPES",
    "NODE_EXECUTOR",
    "NODE_TRANSITIONS",
    "PLANNABLE_NODE_TYPES",
    "PROJECT_TRANSITIONS",
    "SEATED_NODE_TYPES",
    "TERMINAL_NODE_STATUSES",
    "TERMINAL_PROJECT_STATUSES",
    "WORKER_RUN_NODE_TYPES",
    "AcceptanceContract",
    "AcceptanceCriterion",
    "AccessStatus",
    "ActorType",
    "AffectedNodes",
    "AgentIdentity",
    "AgentRole",
    "ApprovalRequest",
    "ApprovalRequirement",
    "ApprovalStatus",
    "Artifact",
    "ArtifactRegistration",
    "ArtifactVersion",
    "AuthorityCheck",
    "AuthorityEnvelope",
    "BudgetLimits",
    "ClaimClass",
    "CompletenessCheck",
    "CompletenessVerdict",
    "CompletionStatus",
    "Confidence",
    "CriterionProvenance",
    "CriterionResult",
    "DagEdge",
    "DagNode",
    "DecisionRecord",
    "DecisionType",
    "DeviationRecord",
    "DisplayPrefix",
    "Evidence",
    "EvidenceConflict",
    "EvidenceSource",
    "EvidenceSourceTier",
    "ExecutionAttempt",
    "ExecutionContract",
    "ExecutionRecord",
    "FailurePolicy",
    "JoinPolicy",
    "MasterCheckpoint",
    "NodeStatus",
    "NodeType",
    "Project",
    "ProjectEvent",
    "ProjectEventType",
    "ProjectMembership",
    "ProjectStatus",
    "ProjectSuccessContract",
    "Record",
    "ResearchContract",
    "ResearchRecord",
    "ReviewCheckpoint",
    "ReviewOutcome",
    "ReviewRecord",
    "Roadmap",
    "RoadmapPhase",
    "Sufficiency",
    "SufficiencyAssessment",
    "TerminationStatus",
    "TransitionCheck",
    "TransitionError",
    "User",
    "UserRole",
    "WorkerMessage",
    "WorkerMessageKind",
    "artifact_key",
    "can_transition_node",
    "can_transition_project",
    "display_id",
    "ensure_utc",
    "executor_for",
    "is_join_satisfied",
    "is_opaque_id",
    "new_id",
    "requires_frozen_criteria",
    "unexecutable_reason",
    "utcnow",
]
